const defaultWords = [
        { word: "abase", meanings: ["비하하다", "낮추다", "떨어뜨리다"] },
        { word: "abash", meanings: ["무안하게 하다", "당황하게 하다"] },
        { word: "abate", meanings: ["줄이다", "완화하다", "가라앉다"] },
        { word: "abbreviate", meanings: ["요약하다", "단축하다", "축약하다"] },
        { word: "abdicate", meanings: ["퇴위하다", "포기하다", "사임하다"] },
        { word: "aberrant", meanings: ["정도를 벗어난", "비정상적인", "일탈적인"] },
        { word: "abet", meanings: ["부추기다", "선동하다", "교사하다"] },
        { word: "abeyance", meanings: ["중지", "정지", "보류"] },
        { word: "abhor", meanings: ["혐오하다", "몹시 싫어하다", "질색하다"] },
        { word: "abide", meanings: ["머무르다", "견디다", "지키다"] },
        { word: "abject", meanings: ["비참한", "절망적인", "비굴한"] },
        { word: "abjure", meanings: ["포기하다", "철회하다", "버리다"] },
        { word: "ablution", meanings: ["목욕", "세면", "재계"] },
        { word: "abnegation", meanings: ["거절", "포기", "자제"] },
        { word: "abode", meanings: ["거주지", "집", "체류"] },
        { word: "abolish", meanings: ["폐지하다", "없애다", "철폐하다"] },
        { word: "abominable", meanings: ["혐오스러운", "끔찍한", "가증스러운"] },
        { word: "aboriginal", meanings: ["원주민의", "토착의", "원래의"] },
        { word: "abortive", meanings: ["실패한", "무산된", "유산의"] },
        { word: "abrade", meanings: ["마모시키다", "찰과상을 입히다"] },
        { word: "abrasive", meanings: ["거친", "불쾌한", "연마재"] },
        { word: "abridge", meanings: ["요약하다", "단축하다", "축소하다"] },
        { word: "abrogate", meanings: ["폐지하다", "철폐하다", "파기하다"] },
        { word: "abscond", meanings: ["도망치다", "자취를 감추다", "도주하다"] },
        { word: "absolute", meanings: ["절대적인", "완전한", "확실한"] },
        { word: "absolve", meanings: ["용서하다", "무죄임을 선언하다", "사면하다"] },
        { word: "abstain", meanings: ["삼가다", "기권하다", "절제하다"] },
        { word: "abstemious", meanings: ["절제하는", "금욕적인", "검소한"] },
        { word: "abstinence", meanings: ["절제", "금욕", "금주"] },
        { word: "abstract", meanings: ["추상적인", "요약하다", "추출하다"] },
        { word: "abstruse", meanings: ["난해한", "심오한", "이해하기 어려운"] },
        { word: "absurd", meanings: ["터무니없는", "불합리한", "어리석은"] },
        { word: "abundant", meanings: ["풍부한", "많은", "넘쳐나는"] },
        { word: "abuse", meanings: ["남용하다", "학대하다", "욕설"] },
        { word: "abysmal", meanings: ["최악의", "끔찍한", "심연의"] },
        { word: "accede", meanings: ["동의하다", "응하다", "취임하다"] },
        { word: "accelerate", meanings: ["가속하다", "촉진하다", "빨라지다"] },
        { word: "accessible", meanings: ["접근 가능한", "이해하기 쉬운"] },
        { word: "accessory", meanings: ["부속물", "액세서리", "종범"] },
        { word: "acclaim", meanings: ["칭송하다", "환호하다", "찬사"] },
        { word: "acclimate", meanings: ["적응하다", "순응하다"] },
        { word: "accolade", meanings: ["포상", "칭찬", "영예"] },
        { word: "accommodate", meanings: ["수용하다", "편의를 도모하다", "적응시키다"] },
        { word: "accomplice", meanings: ["공범", "연루자"] },
        { word: "accord", meanings: ["합의", "일치하다", "부여하다"] },
        { word: "accost", meanings: ["다가가서 말을 걸다"] },
        { word: "accoutrement", meanings: ["장비", "장식", "복장"] },
        { word: "accretion", meanings: ["축적", "증가", "부착"] },
        { word: "accrue", meanings: ["누적되다", "축적하다", "생기다"] },
        { word: "acerbic", meanings: ["신랄한", "가혹한", "쓴"] },
        { word: "acerbity", meanings: ["신랄함", "매서움", "신맛"] },
        { word: "acetic", meanings: ["신맛이 나는", "초산의"] },
        { word: "acidulous", meanings: ["신맛이 나는", "신랄한"] },
        { word: "acknowledge", meanings: ["인정하다", "감사하다", "확인하다"] },
        { word: "acme", meanings: ["절정", "정점", "극치"] },
        { word: "acoustics", meanings: ["음향학", "음향 시설"] },
        { word: "acquiesce", meanings: ["묵인하다", "따르다", "동의하다"] },
        { word: "acquire", meanings: ["얻다", "획득하다", "습득하다"] },
        { word: "acquittal", meanings: ["무죄 선고", "석방"] },
        { word: "acrid", meanings: ["매운", "신랄한", "콕 쏘는"] },
        { word: "acrimonious", meanings: ["신랄한", "험악한", "매서운"] },
        { word: "acumen", meanings: ["예리함", "통찰력", "명민함"] },
        { word: "acute", meanings: ["예리한", "극심한", "급성의"] },
        { word: "adage", meanings: ["속담", "격언"] },
        { word: "adamant", meanings: ["단호한", "요지부동의", "견고한"] },
        { word: "adapt", meanings: ["적응하다", "각색하다", "맞추다"] },
        { word: "addendum", meanings: ["부록", "추가물"] },
        { word: "addiction", meanings: ["중독", "탐닉"] },
        { word: "addle", meanings: ["혼란스럽게 하다", "썩다"] },
        { word: "address", meanings: ["다루다", "연설하다", "주소"] },
        { word: "adept", meanings: ["능숙한", "숙련된", "달인"] },
        { word: "adhere", meanings: ["고수하다", "들러붙다", "부착되다"] },
        { word: "adherent", meanings: ["지지자", "추종자", "접착성의"] },
        { word: "adjacent", meanings: ["인접한", "가까운"] },
        { word: "adjourn", meanings: ["휴회하다", "연기하다"] },
        { word: "adjunct", meanings: ["부속물", "부가물", "조수"] },
        { word: "admonish", meanings: ["훈계하다", "충고하다", "경고하다"] },
        { word: "adorn", meanings: ["장식하다", "꾸미다"] },
        { word: "adroit", meanings: ["능숙한", "솜씨 좋은", "기민한"] },
        { word: "adulation", meanings: ["과도한 칭찬", "아부", "찬사"] },
        { word: "adulterate", meanings: ["불순물을 섞다", "질을 떨어뜨리다"] },
        { word: "advent", meanings: ["출현", "도래"] },
        { word: "adventitious", meanings: ["우연한", "외래의"] },
        { word: "adversary", meanings: ["적", "상대", "원수"] },
        { word: "adverse", meanings: ["부정적인", "불리한", "반대의"] },
        { word: "adversity", meanings: ["역경", "불행", "재난"] },
        { word: "advocacy", meanings: ["옹호", "지지", "변호"] },
        { word: "advocate", meanings: ["옹호하다", "지지하다", "변호사"] },
        { word: "aerie", meanings: ["둥지", "높은 곳에 있는 집"] },
        { word: "aesthetic", meanings: ["미학적인", "심미적인", "미적인"] },
        { word: "affable", meanings: ["상냥한", "붙임성 있는", "친절한"] },
        { word: "affected", meanings: ["가식적인", "영향을 받은", "병에 걸린"] },
        { word: "affidavit", meanings: ["선서 진술서", "진술서"] },
        { word: "affiliation", meanings: ["소속", "가입", "동맹"] },
        { word: "affinity", meanings: ["친밀감", "유사성", "애착"] },
        { word: "affirmation", meanings: ["확언", "단언", "긍정"] },
        { word: "affix", meanings: ["부착하다", "붙이다", "접사"] },
        { word: "affliction", meanings: ["고통", "고뇌", "질병"] },
        { word: "affluence", meanings: ["풍부함", "부유함", "유복"] },
        { word: "affront", meanings: ["모욕", "상처", "모욕하다"] },
        { word: "aftermath", meanings: ["여파", "결과", "후유증"] },
        { word: "agenda", meanings: ["의제", "안건", "예정표"] },
        { word: "agent", meanings: ["대리인", "요원", "매개체"] },
        { word: "agglomeration", meanings: ["응집", "덩어리", "집합체"] },
        { word: "aggrandize", meanings: ["크게 하다", "확대하다", "과장하다"] },
        { word: "aggregate", meanings: ["합계", "총액", "모으다"] },
        { word: "aggressor", meanings: ["침략자", "공격자"] },
        { word: "aghast", meanings: ["경악한", "겁에 질린", "놀란"] },
        { word: "agility", meanings: ["민첩함", "명민함", "기민함"] },
        { word: "agitate", meanings: ["선동하다", "동요시키다", "휘젓다"] },
        { word: "agnostic", meanings: ["불가지론자", "불가지론의"] },
        { word: "alacrity", meanings: ["민첩함", "활기", "선뜻 ~함"] },
        { word: "alias", meanings: ["가명", "별명"] },
        { word: "alienate", meanings: ["소외시키다", "멀어지게 하다", "양도하다"] },
        { word: "alimentary", meanings: ["영양의", "소화의"] },
        { word: "allay", meanings: ["가라앉히다", "완화하다", "진정시키다"] },
        { word: "allege", meanings: ["주장하다", "단언하다", "혐의를 제기하다"] },
        { word: "allegiance", meanings: ["충성", "헌신", "맹세"] },
        { word: "allegory", meanings: ["우화", "풍유", "비유"] },
        { word: "alleviate", meanings: ["완화하다", "경감하다", "덜어주다"] },
        { word: "alliteration", meanings: ["두운법", "두운"] },
        { word: "allocate", meanings: ["할당하다", "배분하다", "배치하다"] },
        { word: "alloy", meanings: ["합금", "섞다", "합금하다"] },
        { word: "allude", meanings: ["암시하다", "넌지시 말하다", "언급하다"] },
        { word: "allure", meanings: ["유혹하다", "매혹하다", "매력"] },
        { word: "allusion", meanings: ["암시", "언급", "빗댐"] },
        { word: "aloft", meanings: ["위로", "높이"] },
        { word: "aloof", meanings: ["냉담한", "거리를 두는", "초연한"] },
        { word: "altercation", meanings: ["언쟁", "논쟁", "격론"] },
        { word: "altruistic", meanings: ["이타적인", "애타적인"] },
        { word: "amalgamate", meanings: ["합병하다", "혼합하다", "융합하다"] },
        { word: "amass", meanings: ["모으다", "축적하다"] },
        { word: "ambidextrous", meanings: ["양손잡이의", "솜씨 좋은", "능숙한"] },
        { word: "ambience", meanings: ["분위기", "환경"] },
        { word: "ambiguous", meanings: ["애매한", "모호한", "두 가지 뜻을 지닌"] },
        { word: "ambivalence", meanings: ["양면 가치", "모순", "주저함"] },
        { word: "amble", meanings: ["느릿느릿 걷다", "산책하다"] },
        { word: "ambulatory", meanings: ["보행의", "이동하는"] },
        { word: "ameliorate", meanings: ["개선하다", "향상시키다", "좋아지다"] },
        { word: "amenable", meanings: ["순종하는", "기꺼이 따르는", "다루기 쉬운"] },
        { word: "amend", meanings: ["수정하다", "개정하다", "고치다"] },
        { word: "amiable", meanings: ["상냥한", "다정한", "우호적인"] },
        { word: "amicable", meanings: ["우호적인", "원만한", "평화적인"] },
        { word: "amiss", meanings: ["잘못된", "틀린", "어긋난"] },
        { word: "amity", meanings: ["우호", "친선", "우정"] },
        { word: "amnesia", meanings: ["기억상실증", "건망증"] },
        { word: "amnesty", meanings: ["사면", "특사", "자진 신고 기간"] },
        { word: "amoral", meanings: ["도덕 관념이 없는", "도덕과 무관한"] },
        { word: "amorous", meanings: ["호색적인", "사랑의", "요염한"] },
        { word: "amorphous", meanings: ["무정형의", "형태가 없는", "애매한"] },
        { word: "amphibian", meanings: ["양서류", "수륙 양용차"] },
        { word: "ample", meanings: ["풍부한", "충분한", "넓은"] },
        { word: "amplify", meanings: ["증폭하다", "확대하다", "상세히 설명하다"] },
        { word: "amputate", meanings: ["절단하다", "자르다"] },
        { word: "anachronism", meanings: ["시대착오", "시대에 뒤떨어진 사람"] },
        { word: "analogous", meanings: ["유사한", "비슷한", "닮은"] },
        { word: "analogy", meanings: ["비유", "유추", "유사점"] },
        { word: "anarchist", meanings: ["무정부주의자"] },
        { word: "anarchy", meanings: ["무정부 상태", "혼란", "무질서"] },
        { word: "anathema", meanings: ["저주", "파문", "절대 반대하는 것"] },
        { word: "ancestry", meanings: ["가계", "혈통", "조상"] },
        { word: "anchor", meanings: ["닻", "닻을 내리다", "고정시키다"] },
        { word: "ancillary", meanings: ["보조적인", "부수적인", "보조의"] },
        { word: "anecdote", meanings: ["일화", "기담", "비화"] },
        { word: "anemia", meanings: ["빈혈"] },
        { word: "anesthetic", meanings: ["마취제", "마취의"] },
        { word: "anguish", meanings: ["고뇌", "고통", "비통"] },
        { word: "angular", meanings: ["각진", "뼈가 앙상한", "모난"] },
        { word: "animadversion", meanings: ["비난", "혹평", "비평"] },
        { word: "animated", meanings: ["활기찬", "생기 있는", "동영상으로 된"] },
        { word: "animosity", meanings: ["적대감", "증오", "반감"] },
        { word: "animus", meanings: ["적의", "원한", "반감"] },
        { word: "annals", meanings: ["연대기", "기록", "역사"] },
        { word: "annihilate", meanings: ["전멸시키다", "완파하다", "무효화하다"] },
        { word: "annotate", meanings: ["주석을 달다", "주해하다"] },
        { word: "annuity", meanings: ["연금"] },
        { word: "annul", meanings: ["무효로 하다", "취소하다", "폐기하다"] },
        { word: "anodyne", meanings: ["진통제", "온건한", "기분을 달래는"] },
        { word: "anoint", meanings: ["기름을 바르다", "임명하다", "성유를 바르다"] },
        { word: "anomalous", meanings: ["변칙적인", "이례적인", "예외적인"] },
        { word: "anomaly", meanings: ["변칙", "이례적인 것", "예외"] },
        { word: "anonymity", meanings: ["익명성", "무명"] },
        { word: "anonymous", meanings: ["익명의", "작자 미상의", "특색 없는"] },
        { word: "antagonism", meanings: ["적대감", "적의", "반감"] },
        { word: "antecede", meanings: ["선행하다", "앞서다"] },
        { word: "antecedents", meanings: ["조상", "선조", "전력"] },
        { word: "antediluvian", meanings: ["태고의", "구식의", "아주 구식인"] },
        { word: "anthem", meanings: ["찬가", "성가", "국가"] },
        { word: "anthology", meanings: ["문집", "명시 선집"] },
        { word: "anthropocentric", meanings: ["인간 중심의"] },
        { word: "anthropoid", meanings: ["유인원", "사람과 비슷한"] },
        { word: "anthropologist", meanings: ["인류학자"] },
        { word: "anthropomorphic", meanings: ["의인화된", "사람의 모습을 한"] },
        { word: "antic", meanings: ["익살스러운", "기괴한", "장난"] },
        { word: "anticlimax", meanings: ["용두사미", "실망스러운 결말"] },
        { word: "antidote", meanings: ["해독제", "해결책", "교정 수단"] },
        { word: "antipathy", meanings: ["반감", "혐오", "적대감"] },
        { word: "antiquated", meanings: ["구식의", "낡은", "시대에 뒤진"] },
        { word: "antique", meanings: ["골동품", "옛날의", "고풍의"] },
        { word: "antiquity", meanings: ["고대", "유물", "오래됨"] },
        { word: "antiseptic", meanings: ["소독제", "방부제", "매우 청결한"] },
        { word: "antithesis", meanings: ["정반대", "대조", "대립"] },
        { word: "apathy", meanings: ["무관심", "냉담", "무감각"] },
        { word: "ape", meanings: ["모방하다", "흉내 내다", "유인원"] },
        { word: "aperture", meanings: ["구멍", "틈", "조리개"] },
        { word: "apex", meanings: ["정점", "절정", "꼭대기"] },
        { word: "aphasia", meanings: ["실어증"] },
        { word: "aphorism", meanings: ["격언", "경구", "잠언"] },
        { word: "apiary", meanings: ["양봉장"] },
        { word: "aplomb", meanings: ["침착함", "태연자약", "자신감"] },
        { word: "apocalyptic", meanings: ["종말론적인", "계시록의", "파괴적인"] },
        { word: "apocryphal", meanings: ["출처가 불분명한", "가짜의", "위경의"] },
        { word: "apogee", meanings: ["정점", "원지점", "최고조"] },
        { word: "apolitical", meanings: ["정치에 무관심한", "비정치적인"] },
        { word: "apologist", meanings: ["옹호자", "변증자"] },
        { word: "apostate", meanings: ["배교자", "변절자", "탈당자"] },
        { word: "apotheosis", meanings: ["신격화", "절정", "극치"] },
        { word: "appall", meanings: ["오싹하게 하다", "질겁하게 하다"] },
        { word: "apparatus", meanings: ["장치", "기구", "조직", "기관"] },
        { word: "apparel", meanings: ["의복", "옷", "복장"] },
        { word: "apparition", meanings: ["유령", "환영", "도깨비"] },
        { word: "appease", meanings: ["달래다", "진정시키다", "양보하다"] },
        { word: "appellation", meanings: ["명칭", "호칭", "직함"] },
        { word: "append", meanings: ["덧붙이다", "첨부하다", "부록으로 달다"] },
        { word: "application", meanings: ["적용", "지원", "애플리케이션"] },
        { word: "apposite", meanings: ["적절한", "딱 들어맞는"] },
        { word: "appraise", meanings: ["평가하다", "감정하다", "살펴보다"] },
        { word: "appreciate", meanings: ["인정하다", "감사하다", "가치가 오르다", "감상하다"] },
        { word: "apprehend", meanings: ["체포하다", "이해하다", "염려하다"] },
        { word: "apprehension", meanings: ["우려", "불안", "체포", "이해"] },
        { word: "apprenticeship", meanings: ["수습 기간", "도제 제도"] },
        { word: "apprise", meanings: ["알리다", "통지하다"] },
        { word: "approbation", meanings: ["승인", "칭찬", "찬양"] },
        { word: "appropriate", meanings: ["적절한", "도용하다", "책정하다"] },
        { word: "apropos", meanings: ["적절한", "시기에 맞는", "~에 관하여"] },
        { word: "aptitude", meanings: ["소질", "적성", "경향"] },
        { word: "aquatic", meanings: ["수생의", "물의"] },
        { word: "arable", meanings: ["경작할 수 있는", "농경에 적합한"] },
        { word: "arbiter", meanings: ["중재자", "판정권자", "결정권자"] },
        { word: "arbitrary", meanings: ["임의적인", "제멋대로의", "독단적인"] },
        { word: "arbitrate", meanings: ["중재하다", "조정하다"] },
        { word: "arboretum", meanings: ["수목원", "식물원"] },
        { word: "arcade", meanings: ["아케이드", "오락실"] },
        { word: "arcane", meanings: ["신비로운", "불가사의한", "비밀의"] },
        { word: "archaeology", meanings: ["고고학"] },
        { word: "archaic", meanings: ["고풍의", "구식의", "고대의"] },
        { word: "archipelago", meanings: ["다도해", "군도"] },
        { word: "archives", meanings: ["기록 보관소", "공문서"] },
        { word: "ardent", meanings: ["열렬한", "불타는 듯한", "열심인"] },
        { word: "arduous", meanings: ["몹시 힘든", "고된", "벅찬"] },
        { word: "argot", meanings: ["은어", "비어"] },
        { word: "aria", meanings: ["아리아", "영창"] },
        { word: "arid", meanings: ["건조한", "무미건조한", "불모의"] },
        { word: "aristocracy", meanings: ["귀족", "귀족 사회"] },
        { word: "armada", meanings: ["함대", "무적함대"] },
        { word: "aromatic", meanings: ["향기로운", "방향성의"] },
        { word: "arousal", meanings: ["각성", "흥분", "자극"] },
        { word: "arraign", meanings: ["기소하다", "고발하다", "규탄하다"] },
        { word: "array", meanings: ["배열", "집합", "정렬시키다", "치장하다"] },
        { word: "arrears", meanings: ["체납금", "밀린 돈"] },
        { word: "arrest", meanings: ["체포하다", "막다", "끌다"] },
        { word: "arrogance", meanings: ["오만", "거만", "건방짐"] },
        { word: "arroyo", meanings: ["작은 계곡", "마른 도랑"] },
        { word: "arsenal", meanings: ["무기고", "병기창"] },
        { word: "articulate", meanings: ["분명히 표현하다", "또렷한", "말을 잘하는"] },
        { word: "artifact", meanings: ["유물", "인공물", "공예품"] },
        { word: "artifice", meanings: ["기만", "속임수", "교묘함"] },
        { word: "artisan", meanings: ["장인", "기능공"] },
        { word: "artless", meanings: ["꾸밈없는", "순진한", "솜씨 없는"] },
        { word: "ascendancy", meanings: ["지배력", "우위", "패권"] },
        { word: "ascertain", meanings: ["알아내다", "확인하다", "규명하다"] },
        { word: "ascetic", meanings: ["금욕적인", "금욕주의자"] },
        { word: "ascribe", meanings: ["~의 탓으로 돌리다", "~의 것으로 간주하다"] },
        { word: "aseptic", meanings: ["무균의", "방부성의", "무감정의"] },
        { word: "ashen", meanings: ["잿빛의", "창백한"] },
        { word: "asinine", meanings: ["어리석은", "터무니없는", "우둔한"] },
        { word: "askance", meanings: ["의심스런 눈으로", "곁눈으로"] },
        { word: "askew", meanings: ["비스듬히", "삐딱하게"] },
        { word: "asperity", meanings: ["신랄함", "거칠음", "가혹함"] },
        { word: "aspersion", meanings: ["비방", "중상", "비난"] },
        { word: "aspirant", meanings: ["열망자", "지원자", "포부가 있는 사람"] },
        { word: "aspire", meanings: ["열망하다", "염원하다", "갈망하다"] },
        { word: "assail", meanings: ["맹렬히 공격하다", "괴롭히다"] },
        { word: "assay", meanings: ["평가하다", "분석하다", "시험하다"] },
        { word: "assent", meanings: ["찬성하다", "동의하다", "승인"] },
        { word: "assert", meanings: ["주장하다", "단언하다", "확고히 하다"] },
        { word: "assiduous", meanings: ["근면한", "끈기 있는", "지세한"] },
        { word: "assimilate", meanings: ["동화되다", "흡수하다", "소화하다"] },
        { word: "assuage", meanings: ["달래다", "완화하다", "누그러뜨리다"] },
        { word: "assumption", meanings: ["가정", "추정", "인수"] },
        { word: "assurance", meanings: ["보장", "확신", "자신감"] },
        { word: "asteroid", meanings: ["소행성"] },
        { word: "astigmatism", meanings: ["난시"] },
        { word: "astral", meanings: ["별의", "성형의"] },
        { word: "astringent", meanings: ["수축시키는", "신랄한", "엄한"] },
        { word: "astronomical", meanings: ["천문학적인", "어마어마한"] },
        { word: "astute", meanings: ["기민한", "눈치 빠른", "영악한"] },
        { word: "asunder", meanings: ["산산이", "뿔뿔이", "떨어져"] },
        { word: "asylum", meanings: ["망명", "피난처", "수용소"] },
        { word: "asymmetric", meanings: ["비대칭의", "불균형의"] },
        { word: "atavism", meanings: ["격세유전", "원시적 본능의 발현"] },
        { word: "atheistic", meanings: ["무신론의"] },
        { word: "atlas", meanings: ["지도책"] },
        { word: "atone", meanings: ["속죄하다", "보상하다", "만회하다"] },
        { word: "atrocity", meanings: ["잔혹 행위", "만행", "흉악"] },
        { word: "atrophy", meanings: ["위축", "퇴화", "쇠퇴하다"] },
        { word: "attain", meanings: ["달성하다", "도달하다", "이루다"] },
        { word: "attest", meanings: ["증명하다", "입증하다", "증언하다"] },
        { word: "attribute", meanings: ["속성", "특성", "~의 탓으로 돌리다"] },
        { word: "attrition", meanings: ["마모", "소모", "감소"] },
        { word: "atypical", meanings: ["이례적인", "비전형적인"] },
        { word: "audacious", meanings: ["대담한", "무모한", "뻔뻔스러운"] },
        { word: "audit", meanings: ["회계 감사", "청강하다"] },
        { word: "augment", meanings: ["증가시키다", "늘리다"] },
        { word: "augury", meanings: ["전조", "조짐", "점"] },
        { word: "august", meanings: ["위엄 있는", "당당한", "존엄한"] },
        { word: "aureole", meanings: ["후광", "광륜"] },
        { word: "auroral", meanings: ["새벽의", "오로라의"] },
        { word: "auspicious", meanings: ["길조의", "상서로운", "유망한"] },
        { word: "austere", meanings: ["엄격한", "금욕적인", "꾸밈없는"] },
        { word: "authenticate", meanings: ["진짜임을 증명하다", "인증하다"] },
        { word: "authoritarian", meanings: ["권위주의적인", "독재적인"] },
        { word: "authoritative", meanings: ["권위 있는", "고압적인"] },
        { word: "autocratic", meanings: ["독재의", "전제적인"] },
        { word: "automaton", meanings: ["자동 장치", "로봇 같은 사람"] },
        { word: "autonomous", meanings: ["자율적인", "자치의", "독립적인"] },
        { word: "autopsy", meanings: ["부검", "시체 해부"] },
        { word: "auxiliary", meanings: ["보조의", "예비의", "조력자"] },
        { word: "avalanche", meanings: ["눈사태", "쇄도"] },
        { word: "avarice", meanings: ["탐욕", "허욕"] },
        { word: "avenge", meanings: ["복수하다", "원수를 갚다"] },
        { word: "aver", meanings: ["단언하다", "주장하다"] },
        { word: "averse", meanings: ["싫어하는", "반대하는"] },
        { word: "aversion", meanings: ["혐오", "반감"] },
        { word: "avert", meanings: ["피하다", "막다", "눈을 돌리다"] },
        { word: "aviary", meanings: ["새장", "조류 사육장"] },
        { word: "avid", meanings: ["열렬한", "탐욕스러운", "열심인"] },
        { word: "avocation", meanings: ["부업", "취미"] },
        { word: "avow", meanings: ["공언하다", "인정하다", "맹세하다"] },
        { word: "avuncular", meanings: ["삼촌 같은", "친절한", "자애로운"] },
        { word: "awe", meanings: ["경외심", "두려움", "경외하게 하다"] },
        { word: "awful", meanings: ["끔찍한", "지독한", "무시무시한"] },
        { word: "awl", meanings: ["송곳"] },
        { word: "awry", meanings: ["빗나간", "엉망인", "구부러진"] },
        { word: "axiom", meanings: ["자명한 이치", "공리", "격언"] },
        { word: "azure", meanings: ["하늘색의", "푸른"] },
        { word: "babble", meanings: ["옹알이하다", "재잘거리다", "횡설수설하다"] },
        { word: "bacchanalian", meanings: ["취해 흥청대는", "야단법석의"] },
        { word: "badger", meanings: ["괴롭히다", "조르다", "오소리"] },
        { word: "badinage", meanings: ["가벼운 농담", "놀림"] },
        { word: "baffle", meanings: ["당황하게 하다", "좌절시키다", "이해할 수 없다"] },
        { word: "bait", meanings: ["미끼", "유혹하다", "괴롭히다"] },
        { word: "baleful", meanings: ["악의적인", "해로운", "재앙의"] },
        { word: "balk", meanings: ["주저하다", "방해하다", "망설이다"] },
        { word: "ballast", meanings: ["바닥짐", "안정기"] },
        { word: "balm", meanings: ["연고", "위안", "진통제"] },
        { word: "balmy", meanings: ["아늑한", "온화한", "향기로운"] },
        { word: "banal", meanings: ["진부한", "평범한", "시시한"] },
        { word: "bandy", meanings: ["주고받다", "퍼뜨리다", "휘어진"] },
	{ word: "barb", meanings: ["가시", "돋친 말"] },
    { word: "barefaced", meanings: ["뻔뻔스러운", "숨김없는"] },
    { word: "baroque", meanings: ["바로크 양식의", "화려한"] },
    { word: "barrage", meanings: ["일제 사격", "연발", "쏟아짐"] },
    { word: "barrister", meanings: ["법정 변호사"] },
    { word: "barter", meanings: ["물물교환하다", "교역하다"] },
    { word: "bask", meanings: ["햇볕을 쬐다", "혜택을 입다"] },
    { word: "bastion", meanings: ["요새", "보루"] },
    { word: "bating", meanings: ["~을 빼고", "~을 제외하고"] },
    { word: "bauble", meanings: ["싸구려 장신구", "겉만 번지르르한 것"] },
    { word: "bawdy", meanings: ["음탕한", "외설적인"] },
    { word: "beatific", meanings: ["축복받은", "기쁨에 넘친"] },
    { word: "beatitude", meanings: ["지상의 행복", "지복"] },
    { word: "bedizen", meanings: ["야하게 치장하다"] },
    { word: "bedraggle", meanings: ["흠뻑 젖게 하다", "엉망으로 만들다"] },
    { word: "befuddle", meanings: ["혼란스럽게 하다", "어리둥절하게 하다"] },
    { word: "beget", meanings: ["낳다", "야기하다"] },
    { word: "begrudge", meanings: ["시기하다", "아까워하다"] },
    { word: "beguile", meanings: ["구슬리다", "매혹하다", "속이다"] },
    { word: "behemoth", meanings: ["거대한 사람", "거물"] },
    { word: "belabor", meanings: ["장황하게 논하다", "공격하다"] },
    { word: "belated", meanings: ["늦은", "뒤늦은"] },
    { word: "beleaguer", meanings: ["포위하다", "괴롭히다"] },
    { word: "belittle", meanings: ["과소평가하다", "얕보다"] },
    { word: "bellicose", meanings: ["호전적인", "싸우기 좋아하는"] },
    { word: "belligerent", meanings: ["적대적인", "교전 중인"] },
    { word: "bemoan", meanings: ["한탄하다", "슬퍼하다"] },
    { word: "bemused", meanings: ["멍한", "어리둥절한"] },
    { word: "benediction", meanings: ["축복", "기도"] },
    { word: "benefactor", meanings: ["후원자", "은인"] },
    { word: "beneficial", meanings: ["유익한", "이로운"] },
    { word: "beneficiary", meanings: ["수혜자", "수령인"] },
    { word: "benevolent", meanings: ["자비로운", "인자한"] },
    { word: "benign", meanings: ["온화한", "친절한", "양성의"] },
    { word: "bent", meanings: ["성향", "소질", "구부러진"] },
    { word: "bequeath", meanings: ["물려주다", "유증하다"] },
    { word: "berate", meanings: ["호통치다", "꾸짖다"] },
    { word: "bereave", meanings: ["앗아가다", "사별하다"] },
    { word: "bereft", meanings: ["상실한", "빼앗긴"] },
    { word: "berserk", meanings: ["미쳐 날뛰는", "광포한"] },
    { word: "beseech", meanings: ["간청하다", "애원하다"] },
    { word: "beset", meanings: ["괴롭히다", "에워싸다"] },
    { word: "besiege", meanings: ["포위하다", "둘러싸다"] },
    { word: "besmirch", meanings: ["더럽히다", "손상시키다"] },
    { word: "bestial", meanings: ["짐승 같은", "잔인한"] },
    { word: "bestow", meanings: ["수여하다", "부여하다"] },
    { word: "betoken", meanings: ["나타내다", "암시하다"] },
    { word: "betray", meanings: ["배신하다", "누설하다", "은연중에 드러내다"] },
    { word: "betroth", meanings: ["약혼시키다"] },
    { word: "bevy", meanings: ["무리", "떼"] },
    { word: "bewail", meanings: ["통곡하다", "비탄하다"] },
    { word: "bewilder", meanings: ["당황하게 하다", "어리둥절하게 하다"] },
    { word: "bewitching", meanings: ["매혹적인", "마음을 빼앗는"] },
    { word: "biased", meanings: ["편향된", "선입견이 있는"] },
    { word: "bicameral", meanings: ["양원제의"] },
    { word: "bicker", meanings: ["말다툼하다", "언쟁하다"] },
    { word: "biennial", meanings: ["2년에 한 번씩의"] },
    { word: "bifurcated", meanings: ["두 갈래로 나뉜"] },
    { word: "bigotry", meanings: ["편협함", "완고함"] },
    { word: "bilious", meanings: ["화를 잘 내는", "성마른"] },
    { word: "bilk", meanings: ["속이다", "사취하다"] },
    { word: "billowing", meanings: ["부풀어 오르는", "소용돌이치는"] },
    { word: "bivouac", meanings: ["야영지", "노숙하다"] },
    { word: "bizarre", meanings: ["기괴한", "별난"] },
    { word: "blanch", meanings: ["창백해지다", "표백하다"] },
    { word: "bland", meanings: ["단조로운", "특징 없는", "부드러운"] },
    { word: "blandishment", meanings: ["감언이설", "추종"] },
    { word: "blase", meanings: ["무관심한", "환멸을 느낀"] },
    { word: "blasphemy", meanings: ["신성모독"] },
    { word: "blatant", meanings: ["노골적인", "뻔뻔스러운"] },
    { word: "bleak", meanings: ["암울한", "절망적인", "황량한"] },
    { word: "blemish", meanings: ["흠", "결점", "오점"] },
    { word: "blight", meanings: ["망치다", "파멸", "병해"] },
    { word: "blithe", meanings: ["쾌활한", "태평스러운"] },
    { word: "bloated", meanings: ["부은", "부푼", "거만한"] },
    { word: "bludgeon", meanings: ["패다", "강요하다", "곤봉"] },
    { word: "bluff", meanings: ["허세", "절벽", "무뚝뚝한"] },
    { word: "blunder", meanings: ["큰 실수", "실수하다"] },
    { word: "blunt", meanings: ["무딘", "직설적인", "둔화시키다"] },
    { word: "blur", meanings: ["흐릿하게 하다", "모호해지다"] },
    { word: "blurt", meanings: ["불쑥 말하다"] },
    { word: "bluster", meanings: ["고함치다", "허세 부리다"] },
    { word: "boding", meanings: ["전조", "조짐"] },
    { word: "bogus", meanings: ["가짜의", "위조의"] },
    { word: "boisterous", meanings: ["떠들썩한", "활기찬"] },
    { word: "bolster", meanings: ["지지하다", "강화하다"] },
    { word: "bombastic", meanings: ["과장된", "허풍 떠는"] },
    { word: "boorish", meanings: ["촌스러운", "무례한"] },
    { word: "bouillon", meanings: ["맑은 고기 수프"] },
    { word: "bountiful", meanings: ["풍부한", "관대한"] },
    { word: "bourgeois", meanings: ["중산층의", "속물적인"] },
    { word: "bovine", meanings: ["소의", "미련한"] },
    { word: "bowdlerize", meanings: ["충격적인 부분을 삭제하다"] },
    { word: "brackish", meanings: ["짭짤한", "불쾌한"] },
    { word: "braggadocio", meanings: ["허풍", "자랑"] },
    { word: "braggart", meanings: ["허풍쟁이"] },
    { word: "brandish", meanings: ["휘두르다", "과시하다"] },
    { word: "bravado", meanings: ["허세", "만용"] },
    { word: "brawn", meanings: ["근육", "체력"] },
    { word: "brazen", meanings: ["뻔뻔스러운", "놋쇠로 만든"] },
    { word: "breach", meanings: ["위반", "붕괴", "갈라진 틈"] },
    { word: "breadth", meanings: ["폭", "너비", "폭넓음"] },
    { word: "brevity", meanings: ["간결함", "짧음"] },
    { word: "bristle", meanings: ["발끈하다", "털이 곤두서다"] },
    { word: "brittle", meanings: ["부서지기 쉬운", "깨지기 쉬운"] },
    { word: "broach", meanings: ["말을 꺼내다", "발의하다"] },
    { word: "brocade", meanings: ["비단", "무늬를 넣은 직물"] },
    { word: "brochure", meanings: ["소책자", "팸플릿"] },
    { word: "brooch", meanings: ["브로치", "장신구"] },
    { word: "browbeat", meanings: ["위협하다", "협박하다"] },
    { word: "browse", meanings: ["훑어보다", "방목하다"] },
    { word: "brunt", meanings: ["타격", "충격", "창끝"] },
    { word: "brusque", meanings: ["무뚝뚝한", "퉁명스러운"] },
    { word: "buccaneer", meanings: ["해적", "악덕 사업가"] },
    { word: "bucolic", meanings: ["전원적인", "목가적인"] },
    { word: "buffoonery", meanings: ["익살", "장난"] },
    { word: "bugaboo", meanings: ["두려운 것", "요괴"] },
    { word: "bullion", meanings: ["금괴", "은괴"] },
    { word: "bulwark", meanings: ["방어물", "성채", "보루"] },
    { word: "bumptious", meanings: ["거만한", "오만한"] },
    { word: "bungle", meanings: ["엉망으로 만들다", "실수하다"] },
    { word: "buoyant", meanings: ["부력이 있는", "낙천적인", "활기찬"] },
    { word: "bureaucracy", meanings: ["관료주의", "관료제"] },
    { word: "burgeon", meanings: ["급증하다", "번성하다"] },
    { word: "burlesque", meanings: ["풍자극", "조롱하다"] },
    { word: "burly", meanings: ["건장한", "건장하고 튼튼한"] },
    { word: "burnish", meanings: ["윤을 내다", "닦다"] },
    { word: "bustle", meanings: ["부산떨다", "붐비다"] },
    { word: "buttress", meanings: ["지지대", "부벽", "지지하다"] },
    { word: "buxom", meanings: ["풍만한", "건강하고 쾌활한"] },
    { word: "cabal", meanings: ["비밀 결사", "음모"] },
    { word: "cache", meanings: ["은닉처", "저장소"] },
    { word: "cacophonous", meanings: ["불협화음의", "귀에 거슬리는"] },
    { word: "cacophony", meanings: ["불협화음", "소음"] },
    { word: "cadaver", meanings: ["시체", "사체"] },
    { word: "cadaverous", meanings: ["시체 같은", "창백한"] },
    { word: "cadence", meanings: ["억양", "리듬", "운율"] },
    { word: "cajole", meanings: ["꼬드기다", "회유하다"] },
    { word: "calamity", meanings: ["재앙", "재난"] },
    { word: "calculated", meanings: ["계산된", "의도적인"] },
    { word: "caldron", meanings: ["큰 솥", "가마솥"] },
    { word: "caliber", meanings: ["구경", "역량", "품질"] },
    { word: "calligraphy", meanings: ["서예", "명필"] },
    { word: "callous", meanings: ["냉담한", "무감각한"] },
    { word: "callow", meanings: ["미숙한", "풋내기인"] },
    { word: "calorific", meanings: ["열을 발생하는", "칼로리의"] },
    { word: "calumny", meanings: ["중상", "비방"] },
    { word: "camaraderie", meanings: ["동지애", "우정"] },
    { word: "cameo", meanings: ["카메오", "카메오 출연"] },
    { word: "camouflage", meanings: ["위장", "위장하다"] },
    { word: "canard", meanings: ["유언비어", "헛소문"] },
    { word: "candor", meanings: ["솔직함", "정직"] },
    { word: "canine", meanings: ["개의", "송곳니"] },
    { word: "canny", meanings: ["약삭빠른", "영리한"] },
    { word: "cant", meanings: ["위선적인 말", "은어"] },
    { word: "cantankerous", meanings: ["성미가 고약한", "심술궂은"] },
    { word: "cantata", meanings: ["칸타타", "교성곡"] },
    { word: "canter", meanings: ["구보", "천천히 달리다"] },
    { word: "canto", meanings: ["편", "장"] },
    { word: "canvass", meanings: ["유세하다", "여론조사하다"] },
    { word: "capacious", meanings: ["널찍한", "큼직한"] },
    { word: "capacity", meanings: ["수용력", "능력", "용량"] },
    { word: "capillary", meanings: ["모세혈관", "모세관의"] },
    { word: "capitulate", meanings: ["항복하다", "굴복하다"] },
    { word: "caprice", meanings: ["변덕", "일시적 기분"] },
    { word: "capricious", meanings: ["변덕스러운", "잘 변하는"] },
    { word: "caption", meanings: ["캡션", "자막"] },
    { word: "captious", meanings: ["흠잡기 잘하는", "말꼬리를 잡는"] },
    { word: "carafe", meanings: ["유리병", "물병"] },
    { word: "carapace", meanings: ["등딱지", "갑각"] },
    { word: "carat", meanings: ["캐럿"] },
    { word: "carcinogenic", meanings: ["발암성의"] },
    { word: "cardinal", meanings: ["주요한", "기본적인", "추기경"] },
    { word: "cardiologist", meanings: ["심장병 전문의"] },
    { word: "careen", meanings: ["위태롭게 달리다", "기울다"] },
    { word: "career", meanings: ["경력", "직업"] },
    { word: "careful", meanings: ["주의 깊은", "조심하는"] },
    { word: "carnage", meanings: ["대량 학살", "살육"] },
    { word: "carnal", meanings: ["육체의", "육욕적인"] },
    { word: "carnivorous", meanings: ["육식성의"] },
    { word: "carping", meanings: ["트집 잡는", "잔소리 심한"] },
    { word: "cartographer", meanings: ["지도 제작자"] },
    { word: "cascade", meanings: ["작은 폭포", "폭포처럼 떨어지다"] },
    { word: "castigate", meanings: ["크게 책망하다", "징계하다"] },
    { word: "casualty", meanings: ["사상자", "피해자"] },
    { word: "cataclysm", meanings: ["대재앙", "대변동"] },
    { word: "catalyst", meanings: ["촉매", "기폭제"] },
    { word: "catapult", meanings: ["투석기", "새총", "쏘아 올리다"] },
    { word: "cataract", meanings: ["큰 폭포", "백내장"] },
    { word: "catastrophe", meanings: ["대참사", "재앙"] },
    { word: "catcall", meanings: ["야유", "야유하다"] },
    { word: "catechism", meanings: ["교리 문답", "문답식 교육"] },
    { word: "categorical", meanings: ["단정적인", "절대적인"] },
    { word: "cathartic", meanings: ["카타르시스의", "배변의"] },
    { word: "catholic", meanings: ["보편적인", "폭넓은"] },
    { word: "caucus", meanings: ["간부회의", "전당대회"] },
    { word: "causal", meanings: ["인과 관계의", "원인이 되는"] },
    { word: "caustic", meanings: ["신랄한", "부식성의"] },
    { word: "cauterize", meanings: ["지지다", "뜸질하다"] },
    { word: "cavalcade", meanings: ["기마 행렬", "퍼레이드"] },
    { word: "cavalier", meanings: ["무신경한", "거만한"] },
    { word: "cavil", meanings: ["트집 잡다"] },
    { word: "cede", meanings: ["양도하다", "이양하다"] },
    { word: "celerity", meanings: ["민첩함", "신속함"] },
    { word: "celestial", meanings: ["하늘의", "천체의"] },
    { word: "celibate", meanings: ["독신주의자", "금욕하는"] },
    { word: "censor", meanings: ["검열하다", "검열관"] },
    { word: "censorious", meanings: ["비판적인", "트집 잡는"] },
    { word: "censure", meanings: ["비난", "책망", "비난하다"] },
    { word: "centaur", meanings: ["켄타우로스"] },
    { word: "centigrade", meanings: ["섭씨의"] },
    { word: "centrifugal", meanings: ["원심력의", "밖으로 향하는"] },
    { word: "centripetal", meanings: ["구심력의", "중심으로 향하는"] },
    { word: "centurion", meanings: ["백부장", "지휘관"] },
    { word: "cerebral", meanings: ["뇌의", "지적인"] },
    { word: "cerebration", meanings: ["사고", "사색"] },
    { word: "ceremonious", meanings: ["의식의", "지나치게 격식을 갖춘"] },
    { word: "certitude", meanings: ["확신", "확실성"] },
    { word: "cessation", meanings: ["중단", "중지"] },
    { word: "cession", meanings: ["양도", "이양"] },
    { word: "chafe", meanings: ["짜증나게 하다", "마찰시키다"] },
    { word: "chaff", meanings: ["왕겨", "가치 없는 것"] },
    { word: "chaffing", meanings: ["조롱", "농담"] },
    { word: "chagrin", meanings: ["원통함", "분함"] },
    { word: "chalice", meanings: ["성배", "잔"] },
    { word: "chameleon", meanings: ["카멜레온", "변덕스러운 사람"] },
    { word: "champion", meanings: ["옹호하다", "지지하다"] },
    { word: "chaotic", meanings: ["혼돈 상태인", "무질서한"] },
    { word: "charisma", meanings: ["카리스마", "매력"] },
    { word: "charlatan", meanings: ["돌팔이", "사기꾼"] },
    { word: "chary", meanings: ["조심하는", "신중한"] },
    { word: "chasm", meanings: ["깊은 틈", "균열", "차이"] },
    { word: "chassis", meanings: ["섀시", "차대"] },
    { word: "chaste", meanings: ["순결한", "정숙한"] },
    { word: "chasten", meanings: ["훈계하다", "징벌하다"] },
    { word: "chastise", meanings: ["꾸짖다", "태형을 가하다"] },
    { word: "chauvinist", meanings: ["맹목적 애국주의자", "차별주의자"] },
    { word: "check", meanings: ["저지하다", "억제하다"] },
    { word: "checkered", meanings: ["파란만장한", "변화가 많은"] },
    { word: "cherubic", meanings: ["천사 같은", "순진한"] },
    { word: "chide", meanings: ["꾸짖다", "책망하다"] },
    { word: "chimerical", meanings: ["공상적인", "터무니없는"] },
    { word: "chisel", meanings: ["끌", "조각하다", "속이다"] },
    { word: "chivalrous", meanings: ["기사도적인", "예의 바른"] },
    { word: "choice", meanings: ["우수한", "고급의"] },
    { word: "choleric", meanings: ["화를 잘 내는", "성마른"] },
    { word: "choreography", meanings: ["안무", "안무법"] },
    { word: "chortle", meanings: ["깔깔 웃다", "기뻐하다"] },
    { word: "chronicle", meanings: ["연대기", "기록하다"] },
    { word: "churlish", meanings: ["무례한", "야비한", "버릇없는"] },
    { word: "cipher", meanings: ["암호", "하찮은 사람", "계산하다"] },
    { word: "circuitous", meanings: ["우회하는", "빙 돌아가는"] },
    { word: "circumlocution", meanings: ["에둘러 말하기", "완곡한 표현"] },
    { word: "circumscribe", meanings: ["제한하다", "둘레에 선을 긋다"] },
    { word: "circumvent", meanings: ["피하다", "우회하다", "교묘히 회피하다"] },
    { word: "citadel", meanings: ["요새", "성채", "보루"] },
    { word: "cite", meanings: ["인용하다", "소환하다", "언급하다"] },
    { word: "clairvoyant", meanings: ["천리안이 있는", "통찰력 있는"] },
    { word: "clamber", meanings: ["기어오르다", "기어 올라가다"] },
    { word: "clamor", meanings: ["아우성", "떠들썩함", "강력히 요구하다"] },
    { word: "clangor", meanings: ["땡그랑거리는 소리", "시끄러운 소리"] },
    { word: "cleave", meanings: ["쪼개다", "착 달라붙다", "고수하다"] },
    { word: "clemency", meanings: ["관대함", "자비", "온화함"] },
    { word: "cliché", meanings: ["진부한 표현", "상투적인 문구"] },
    { word: "clientele", meanings: ["고객들", "단골손님"] },
    { word: "climactic", meanings: ["절정의", "클라이맥스의"] },
    { word: "clique", meanings: ["파벌", "패당"] },
    { word: "cloister", meanings: ["수도원", "은둔하다"] },
    { word: "clout", meanings: ["영향력", "권력", "때리기"] },
    { word: "cloying", meanings: ["질릴 정도인", "역겨울 정도로 단"] },
    { word: "coagulate", meanings: ["응고하다", "굳어지다"] },
    { word: "coalition", meanings: ["연합", "합동", "제휴"] },
    { word: "coddle", meanings: ["관대하게 대하다", "응석을 받아주다"] },
    { word: "coerce", meanings: ["강요하다", "강제하다"] },
    { word: "cogitate", meanings: ["숙고하다", "곰곰이 생각하다"] },
    { word: "cognate", meanings: ["어원이 같은", "유사한"] },
    { word: "cognitive", meanings: ["인지의", "인식의"] },
    { word: "cognizance", meanings: ["인식", "인지", "지각"] },
    { word: "cohere", meanings: ["밀착하다", "일관성이 있다"] },
    { word: "cohesion", meanings: ["결합", "응집력", "유대"] },
    { word: "cohort", meanings: ["집단", "무리", "동료"] },
    { word: "coin", meanings: ["신조어를 만들다", "주조하다"] },
    { word: "coincide", meanings: ["동시에 일어나다", "일치하다"] },
    { word: "collaborate", meanings: ["협력하다", "공동으로 작업하다"] },
    { word: "collateral", meanings: ["담보", "부수적인", "나란히 있는"] },
    { word: "colloquial", meanings: ["구어체의", "일상 회화의"] },
    { word: "colossal", meanings: ["거대한", "엄청난"] },
    { word: "comatose", meanings: ["혼수상태의", "몹시 졸리는"] },
    { word: "combustible", meanings: ["가연성의", "불붙기 쉬운"] },
    { word: "comely", meanings: ["아름다운", "매력적인"] },
    { word: "comestible", meanings: ["먹을 수 있는", "식료품"] },
    { word: "comeuppance", meanings: ["마땅한 벌", "응보"] },
    { word: "commandeer", meanings: ["징발하다", "탈취하다"] },
    { word: "commemorate", meanings: ["기념하다", "축하하다"] },
    { word: "commensurate", meanings: ["상응하는", "비례하는", "어울리는"] },
    { word: "commiserate", meanings: ["동정하다", "위로하다"] },
    { word: "commodious", meanings: ["넓은", "널찍한"] },
    { word: "communal", meanings: ["공동의", "공용의"] },
    { word: "compact", meanings: ["소형의", "조밀한", "계약"] },
    { word: "comparable", meanings: ["비슷한", "비교할 만한"] },
    { word: "compelling", meanings: ["설득력 있는", "강렬한"] },
    { word: "compendium", meanings: ["개요", "요약", "요약본"] },
    { word: "compensatory", meanings: ["보상의", "보충적인"] },
    { word: "compile", meanings: ["편집하다", "수집하다"] },
    { word: "complaisant", meanings: ["남의 뜻에 잘 따르는", "고분고분한"] },
    { word: "complement", meanings: ["보완하다", "보충물"] },
    { word: "compliance", meanings: ["준수", "따름", "순응"] },
    { word: "compliant", meanings: ["순응하는", "따르는"] },
    { word: "complicity", meanings: ["공모", "연루"] },
    { word: "comply", meanings: ["따르다", "준수하다"] },
    { word: "component", meanings: ["구성 요소", "성분"] },
    { word: "comport", meanings: ["처신하다", "행동하다", "어울리다"] },
    { word: "composure", meanings: ["침착", "평정"] },
    { word: "compound", meanings: ["혼합물", "악화시키다", "합성하다"] },
    { word: "comprehensive", meanings: ["포괄적인", "종합적인"] },
    { word: "comprise", meanings: ["구성되다", "포함하다"] },
    { word: "compromise", meanings: ["타협하다", "위태롭게 하다", "절충안"] },
    { word: "compunction", meanings: ["양심의 가책", "뉘우침"] },
    { word: "compute", meanings: ["계산하다", "산출하다"] },
    { word: "concatenate", meanings: ["사슬같이 잇다", "연결하다"] },
    { word: "concede", meanings: ["인정하다", "수긍하다", "내주다"] },
    { word: "conceit", meanings: ["자만심", "자부심"] },
    { word: "concentric", meanings: ["동심원의", "중심이 같은"] },
    { word: "conception", meanings: ["개념", "구상", "임신"] },
    { word: "concession", meanings: ["양보", "인정", "구내매점"] },
    { word: "conciliate", meanings: ["달래다", "회유하다", "조정하다"] },
    { word: "concise", meanings: ["간결한", "축약된"] },
    { word: "conclusive", meanings: ["결정적인", "확실한"] },
    { word: "concoct", meanings: ["조작하다", "꾸며내다"] },
    { word: "concomitant", meanings: ["수반되는", "동시에 일어나는"] },
    { word: "concord", meanings: ["일치", "조화", "화합"] },
    { word: "concur", meanings: ["동의하다", "일치하다"] },
    { word: "concurrent", meanings: ["동시 발생의", "공존하는"] },
    { word: "condescend", meanings: ["자신을 낮추다", "거들먹거리다"] },
    { word: "condign", meanings: ["적절한", "타당한"] },
    { word: "condiments", meanings: ["양념", "조미료"] },
    { word: "condole", meanings: ["위로하다", "애도하다"] },
    { word: "condone", meanings: ["용서하다", "눈감아주다"] },
    { word: "conducive", meanings: ["도움이 되는", "이바지하는"] },
    { word: "conduit", meanings: ["도관", "전선관", "매개체"] },
    { word: "confidant", meanings: ["비밀을 털어놓을 수 있는 친구"] },
    { word: "confide", meanings: ["비밀을 털어놓다", "신뢰하다"] },
    { word: "confidence", meanings: ["신뢰", "자신감", "비밀"] },
    { word: "confiscate", meanings: ["몰수하다", "압수하다"] },
    { word: "conflagration", meanings: ["큰불", "대화재"] },
    { word: "confluence", meanings: ["합류", "집합", "융합"] },
    { word: "confound", meanings: ["어리둥절하게 하다", "혼란스럽게 하다"] },
    { word: "congeal", meanings: ["응고시키다", "얼리다"] },
    { word: "congenial", meanings: ["마음이 맞는", "친근한", "적절한"] },
    { word: "congenital", meanings: ["선천적인", "타고난"] },
    { word: "conglomeration", meanings: ["복합체", "덩어리", "집성체"] },
    { word: "congruence", meanings: ["적합", "일치", "합동"] },
    { word: "conifer", meanings: ["침엽수"] },
    { word: "conjecture", meanings: ["추측하다", "짐작하다", "추측"] },
    { word: "conjugal", meanings: ["부부의", "혼인의"] },
    { word: "conjure", meanings: ["마술을 부리다", "상기시키다"] },
    { word: "connivance", meanings: ["묵인", "방조", "공모"] },
    { word: "connoisseur", meanings: ["감정가", "전문가", "감식가"] },
    { word: "connotation", meanings: ["함축", "내포된 의미"] },
    { word: "connubial", meanings: ["부부의", "결혼의"] },
    { word: "consanguinity", meanings: ["혈족", "친족 관계"] },
    { word: "conscript", meanings: ["징집하다", "징집병"] },
    { word: "consecrate", meanings: ["신성하게 하다", "봉헌하다"] },
    { word: "consensus", meanings: ["의견 일치", "합의"] },
    { word: "consequential", meanings: ["중요한", "결과로서 일어나는"] },
    { word: "conservatory", meanings: ["온실", "음악 학교"] },
    { word: "consign", meanings: ["위탁하다", "맡기다", "할당하다"] },
    { word: "consistency", meanings: ["일관성", "농도", "밀도"] },
    { word: "console", meanings: ["위로하다", "제어반"] },
    { word: "consolidation", meanings: ["합병", "강화", "정리"] },
    { word: "consonance", meanings: ["일치", "조화", "화음"] },
    { word: "consort", meanings: ["배우자", "동료", "어울리다"] },
    { word: "conspicuous", meanings: ["눈에 띄는", "뚜렷한"] },
    { word: "conspiracy", meanings: ["음모", "모의"] },
    { word: "constituent", meanings: ["구성하는", "유권자", "성분"] },
    { word: "constraint", meanings: ["제약", "제한", "통제"] },
    { word: "construe", meanings: ["해석하다", "이해하다"] },
    { word: "consummate", meanings: ["완벽한", "완성하다", "능숙한"] },
    { word: "contagion", meanings: ["전염", "전염병"] },
    { word: "contaminate", meanings: ["오염시키다", "더럽히다"] },
    { word: "contempt", meanings: ["경멸", "멸시"] },
    { word: "contend", meanings: ["주장하다", "다투다", "겨루다"] },
    { word: "contention", meanings: ["논쟁", "주장", "말다툼"] },
    { word: "contentious", meanings: ["논쟁을 좋아하는", "논쟁을 초래하는"] },
    { word: "contest", meanings: ["대회", "다투다", "이의를 제기하다"] },
    { word: "context", meanings: ["문맥", "정황", "맥락"] },
    { word: "contiguous", meanings: ["인접한", "이웃한", "접촉하는"] },
    { word: "continence", meanings: ["자제", "금욕", "절제"] },
    { word: "contingent", meanings: ["~에 달려있는", "대표단", "파견대"] },
    { word: "contortions", meanings: ["비틀림", "일그러짐", "기형"] },
    { word: "contraband", meanings: ["밀수품", "밀수"] },
    { word: "contravene", meanings: ["위반하다", "모순되다", "반박하다"] },
    { word: "contrite", meanings: ["깊이 뉘우치는", "회개하는"] },
    { word: "contrition", meanings: ["뉘우침", "회개"] },
    { word: "contrive", meanings: ["고안하다", "획책하다"] },
    { word: "controvert", meanings: ["반박하다", "부인하다"] },
    { word: "contumacious", meanings: ["반항적인", "반역의"] },
    { word: "contusion", meanings: ["타박상", "좌상"] },
    { word: "convene", meanings: ["소집하다", "모이다"] },
    { word: "convention", meanings: ["관습", "대회", "조약"] },
    { word: "conventional", meanings: ["전통적인", "틀에 박힌", "관습적인"] },
    { word: "converge", meanings: ["모이다", "집중되다"] },
    { word: "conversant", meanings: ["~에 친숙한", "정통한"] },
    { word: "converse", meanings: ["대화하다", "정반대의"] },
    { word: "convert", meanings: ["전환하다", "개종시키다"] },
    { word: "convex", meanings: ["볼록한"] },
    { word: "conveyance", meanings: ["수송", "전달", "양도"] },
    { word: "conviction", meanings: ["유죄 판결", "강한 신념", "확신"] },
    { word: "convivial", meanings: ["명랑한", "유쾌한", "친목의"] },
    { word: "convoke", meanings: ["소집하다", "불러 모으다"] },
    { word: "convoluted", meanings: ["복잡한", "뒤얽힌", "구불구불한"] },
    { word: "cordial", meanings: ["화기애애한", "다정한", "진심에서 우러난"] },
    { word: "cordon", meanings: ["저지선", "비상선", "차단하다"] },
    { word: "cornucopia", meanings: ["풍요의 뿔", "풍부", "보고"] },
    { word: "corollary", meanings: ["필연적 결과", "당연한 귀결"] },
    { word: "coronation", meanings: ["대관식"] },
    { word: "corporeal", meanings: ["육체의", "물질적인", "유형의"] },
    { word: "corpulent", meanings: ["뚱뚱한", "살찐", "비만의"] },
    { word: "corpus", meanings: ["집대성", "자료체", "전집"] },
    { word: "corpuscle", meanings: ["혈구", "미립자"] },
    { word: "correlate", meanings: ["연관성을 보여주다", "상관관계가 있다"] },
    { word: "correlation", meanings: ["상관관계", "연관성"] },
    { word: "corrosive", meanings: ["부식성의", "좀먹는", "신랄한"] },
    { word: "corrugated", meanings: ["물결 모양의", "주름진"] },
    { word: "cosmic", meanings: ["우주의", "어마어마한", "무한한"] },
    { word: "coterie", meanings: ["배타적인 집단", "동인", "동아리"] },
    { word: "countenance", meanings: ["얼굴 표정", "지지하다", "동의하다"] },
    { word: "countermand", meanings: ["취소하다", "철회하다"] },
    { word: "counterpart", meanings: ["상대방", "대응 관계에 있는 사람"] },
    { word: "coup", meanings: ["쿠데타", "대성공", "일격"] },
    { word: "couple", meanings: ["결합하다", "연결하다", "짝"] },
    { word: "courier", meanings: ["운반원", "안내원", "밀사"] },
    { word: "covenant", meanings: ["계약", "서약", "맹약"] },
    { word: "covert", meanings: ["비밀의", "은밀한"] },
    { word: "covetous", meanings: ["탐내는", "갈망하는"] },
    { word: "cow", meanings: ["위협하다", "겁을 주다", "암소"] },
    { word: "cower", meanings: ["겁을 먹고 움츠리다", "위축되다"] },
    { word: "coy", meanings: ["수줍어하는", "내숭을 떠는", "가식적인"] },
    { word: "cozen", meanings: ["속이다", "기만하다"] },
    { word: "crabbed", meanings: ["심술궂은", "괴팍한", "알아보기 힘든"] },
    { word: "craft", meanings: ["공예", "기술", "술수"] },
    { word: "crass", meanings: ["무신경한", "거친", "우둔한"] },
    { word: "cravat", meanings: ["크라바트", "넥타이"] },
    { word: "credence", meanings: ["신빙성", "믿음", "신임"] },
    { word: "credo", meanings: ["신조", "사도 신경"] },
    { word: "credulity", meanings: ["쉽게 믿음", "순진함"] },
    { word: "creed", meanings: ["신조", "신념", "교리"] },
    { word: "crescendo", meanings: ["점점 커짐", "최고조"] },
    { word: "crestfallen", meanings: ["풀이 죽은", "의기소침한"] },
    { word: "crevice", meanings: ["갈라진 틈", "균열"] },
    { word: "cringe", meanings: ["움츠리다", "민망해하다", "아부하다"] },
    { word: "criteria", meanings: ["기준", "표준"] },
    { word: "crone", meanings: ["노파", "노추"] },
    { word: "crotchety", meanings: ["화를 잘 내는", "신경질적인"] },
    { word: "crux", meanings: ["핵심", "가장 중요한 부분", "십자가"] },
    { word: "crypt", meanings: ["지하실", "납골당"] },
    { word: "cubicle", meanings: ["좁은 방", "칸막이한 공간"] },
    { word: "culinary", meanings: ["요리의", "주방의"] },
    { word: "cull", meanings: ["고르다", "추려내다", "도태시키다"] },
    { word: "culminate", meanings: ["절정에 달하다", "끝이 나다"] },
    { word: "culpable", meanings: ["과실이 있는", "비난받을 만한"] },
    { word: "culvert", meanings: ["지하 배수로", "수로"] },
    { word: "cumbersome", meanings: ["크고 무거운", "다루기 힘든"] },
    { word: "cumulative", meanings: ["누적되는", "점진적인"] },
    { word: "cupidity", meanings: ["탐욕", "물욕"] },
    { word: "curator", meanings: ["큐레이터", "전시 책임자"] },
    { word: "curmudgeon", meanings: ["심술궂은 구두쇠", "괴팍한 사람"] },
    { word: "cursive", meanings: ["필기체의", "흘림체의"] },
    { word: "cursory", meanings: ["대충 하는", "피상적인", "서두르는"] },
    { word: "curtail", meanings: ["축소하다", "삭감하다", "단축하다"] },
    { word: "cynical", meanings: ["냉소적인", "비꼬는"] },
    { word: "cynosure", meanings: ["주목의 대상", "지침", "북극성"] },
    { word: "dabble", meanings: ["취미 삼아 해보다", "첨벙거리다"] },
    { word: "dally", meanings: ["꾸물거리다", "가지고 놀다", "농닥하다"] },
    { word: "dank", meanings: ["축축한", "눅눅한"] },
    { word: "dapper", meanings: ["말끔한", "깔끔한", "단정한"] },
    { word: "dappled", meanings: ["얼룩덜룩한", "반점이 있는"] },
    { word: "daub", meanings: ["칠하다", "더럽히다"] },
    { word: "daunt", meanings: ["겁먹게 하다", "기죽이다"] },
    { word: "dauntless", meanings: ["불굴의", "겁 없는", "용감한"] },
    { word: "dawdle", meanings: ["꾸물거리다", "시간을 낭비하다"] },
    { word: "deadlock", meanings: ["교착 상태", "막다른 골목"] },
    { word: "deadpan", meanings: ["무표정한", "진지한 표정의"] },
    { word: "debase", meanings: ["가치를 떨어뜨리다", "품위를 저하시키다"] },
    { word: "debauch", meanings: ["타락시키다", "방탕하게 하다"] },
    { word: "debonair", meanings: ["멋진", "사교적인", "명랑한"] },
    { word: "debunk", meanings: ["틀렸음을 드러내다", "정체를 폭로하다"] },
    { word: "debutante", meanings: ["사교계에 첫 선을 보이는 여성"] },
    { word: "decadence", meanings: ["타락", "퇴폐", "쇠퇴"] },
    { word: "decadent", meanings: ["타락한", "퇴폐적인"] },
    { word: "decapitate", meanings: ["목을 베다", "해고하다"] },
    { word: "decelerate", meanings: ["속도를 줄이다", "감속하다"] },
    { word: "decimate", meanings: ["대량 살육하다", "심하게 훼손하다"] },
    { word: "decipher", meanings: ["해독하다", "판독하다", "알아내다"] },
    { word: "declivity", meanings: ["내리막길", "경사"] },
    { word: "decollete", meanings: ["목덜미를 판", "노출이 심한"] },
    { word: "decomposition", meanings: ["분해", "부패"] },
    { word: "decorum", meanings: ["점잖음", "예의", "단정함"] },
    { word: "decoy", meanings: ["미끼", "유인하다"] },
    { word: "decrepit", meanings: ["노후한", "노쇠한"] },
    { word: "decry", meanings: ["비난하다", "헐뜯다"] },
    { word: "deducible", meanings: ["추론할 수 있는"] },
    { word: "deface", meanings: ["외관을 훼손하다"] },
    { word: "defame", meanings: ["비방하다", "중상하다"] },
    { word: "default", meanings: ["채무 불이행", "기권"] },
    { word: "defeatist", meanings: ["패배주의자"] },
    { word: "defection", meanings: ["변절", "탈당", "망명"] },
    { word: "defer", meanings: ["미루다", "연기하다", "경의를 표하다"] },
    { word: "deference", meanings: ["존중", "경의"] },
    { word: "defiance", meanings: ["반항", "저항"] },
    { word: "defile", meanings: ["더럽히다", "모독하다"] },
    { word: "definitive", meanings: ["결정적인", "최종적인"] },
    { word: "deflect", meanings: ["방향을 바꾸다", "피하다"] },
    { word: "defoliate", meanings: ["잎을 떨어뜨리다", "고엽제를 뿌리다"] },
    { word: "defray", meanings: ["비용을 부담하다", "지출하다"] },
    { word: "deft", meanings: ["능숙한", "솜씨 좋은"] },
    { word: "defunct", meanings: ["노후한", "더 이상 존재하지 않는"] },
    { word: "degenerate", meanings: ["퇴보하다", "타락하다"] },
    { word: "degradation", meanings: ["타락", "퇴보", "강등"] },
    { word: "dehydrate", meanings: ["건조시키다", "탈수 상태가 되다"] },
    { word: "deify", meanings: ["신격화하다", "숭배하다"] },
    { word: "deign", meanings: ["자신을 낮추어 하다", "황송하게도 해주다"] },
    { word: "deleterious", meanings: ["해로운", "유해한"] },
    { word: "deliberate", meanings: ["고의의", "신중한", "숙고하다"] },
    { word: "delineate", meanings: ["상세히 묘사하다", "윤곽을 그리다"] },
    { word: "delirium", meanings: ["섬망", "망상", "무아지경"] },
    { word: "delude", meanings: ["속이다", "기만하다"] },
    { word: "deluge", meanings: ["폭우", "쇄도", "범람시키다"] },
    { word: "delusion", meanings: ["망상", "착각"] },
    { word: "delve", meanings: ["철저히 조사하다", "탐구하다"] },
    { word: "demagogue", meanings: ["선동 정치가"] },
    { word: "demean", meanings: ["품위를 떨어뜨리다", "비하하다"] },
    { word: "demeanor", meanings: ["품행", "태도"] },
    { word: "demented", meanings: ["정신 착란의", "미친"] },
    { word: "demise", meanings: ["종말", "사망", "죽음"] },
    { word: "demographic", meanings: ["인구학의", "인구 통계학의"] },
    { word: "demolition", meanings: ["파괴", "폭파"] },
    { word: "demoniac", meanings: ["악마의", "광란의"] },
    { word: "demur", meanings: ["이의를 제기하다", "반대하다"] },
    { word: "demure", meanings: ["얌전한", "조신한"] },
    { word: "denigrate", meanings: ["비하하다", "모욕하다"] },
    { word: "denizen", meanings: ["주민", "거주자"] },
    { word: "denomination", meanings: ["교파", "종파", "액면가"] },
    { word: "denotation", meanings: ["명시적 의미", "지시"] },
    { word: "denouement", meanings: ["대단원", "결말"] },
    { word: "denounce", meanings: ["비난하다", "고발하다"] },
    { word: "depict", meanings: ["묘사하다", "그리다"] },
    { word: "deplete", meanings: ["고갈시키다", "대폭 감소시키다"] },
    { word: "deplore", meanings: ["개탄하다", "비판하다"] },
    { word: "deploy", meanings: ["배치하다", "전개하다"] },
    { word: "depose", meanings: ["물러나게 하다", "퇴위시키다"] },
    { word: "deposition", meanings: ["퇴위", "선서 증언", "퇴적물"] },
    { word: "depravity", meanings: ["타락", "부패", "악행"] },
    { word: "deprecate", meanings: ["반대하다", "비난하다"] },
    { word: "depreciatory", meanings: ["경시하는", "가치를 떨어뜨리는"] },
    { word: "depredation", meanings: ["약탈", "파괴"] },
    { word: "deranged", meanings: ["미친", "정신 착란의"] },
    { word: "derelict", meanings: ["버려진", "직무 태만의"] },
    { word: "deride", meanings: ["조롱하다", "비웃다"] },
    { word: "derivative", meanings: ["파생적인", "새롭지 않은"] },
    { word: "derogatory", meanings: ["경멸적인", "비판적인"] },
    { word: "descry", meanings: ["알아보다", "발견하다"] },
    { word: "desecrate", meanings: ["신성 모독하다", "훼손하다"] },
    { word: "desiccate", meanings: ["건조시키다", "생기를 잃게 하다"] },
        { word: "bane", meanings: ["골칫거리", "파멸의 원인", "맹독"] },
        { word: "bantering", meanings: ["농담하는", "놀리는"] }
    ];
        